[common]
# 井号#代表注释，可使该行的内容无效（1开启，0关闭）

# 调试
is_debug=0

# 满仓时自动卖鱼（占用鼠标，一键售出）
is_auto_sell=0

# 无饵时自动买饵（*固定买商店第二个位置的万能鱼饵，如果位置不对则无效，占用鼠标，用渔币买万能鱼饵*99）
is_auto_buy=0

# 断线重连（占用鼠标，点击进入游戏->按F进入钓鱼）
is_re_link=0

# 截取模板（开启时不会钓鱼，而是监控鼠标中键框选矩形模板，记录坐标并保存到本地）
is_cut_tpl=0